name: Test TypeScript code on Node.js >=18.x and latest

on:
  # Allow this workflow to be reused/called
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        description: OS type to run this job on
        default: ubuntu-latest

jobs:
  test:
    name: Test Go code  
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Run tests
        run: go test -v ./...

